CREATE TABLE IF NOT EXISTS Patient (
    PatientID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
	Address1 VARCHAR(100) NULL,
	Address2 VARCHAR(100) NULL,
	City VARCHAR(100) NULL,
	State VARCHAR(50) NULL,
	PostalCode VARCHAR(5) NULL,
	PrimaryPhone VARCHAR(20) NOT NULL,
	Email VARCHAR(255) NULL,
    DOB DATETIME NOT NULL,
	Active BIT NOT NULL DEFAULT(1),
	CreatedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INTEGER NOT NULL,
	LastModifiedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModifiedBy INTEGER NOT NULL,
	Deleted BIT NOT NULL DEFAULT(0)    
);

CREATE TABLE IF NOT EXISTS [User] (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
	Username VARCHAR(25) UNIQUE NOT NULL,
    [Password] VARCHAR(100) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
	Active BIT NOT NULL DEFAULT(1),
	CreatedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedBy INTEGER NOT NULL,
	LastModifiedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LastModifiedBy INTEGER NOT NULL,
	Deleted BIT NOT NULL DEFAULT(0)    
);